# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [53]:
import pandas as pd
import numpy as np

In [54]:
pd.__version__

'3.0.6'

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [55]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [56]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [57]:
chipo["item_price"] = pd.to_numeric(
    chipo["item_price"].astype(str).str.replace("$", ""),
    errors="coerce" # no se para con el error, deja un NaN
)

chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [58]:
print(chipo.loc[chipo["item_price"].idxmax(), ["item_name", "item_price", "quantity"]]) #poner siempre el lic, vas por los indices explicitos, por los nombres de las filas
#de la columna price, el mas alto, y del mas alto quiero ver el nombre, el precio y la cantidad

item_name     Chips and Fresh Tomato Salsa
item_price                           44.25
quantity                                15
Name: 3598, dtype: object

In [59]:
#para sber el producto más caro por unidad se divide el item price entre la cantidad.
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

### Step 3. Name of the max valued product

In [60]:

fila_maxima = chipo['item_price'].idxmax()

articulo_mas_caro = chipo.loc[fila_maxima, 'item_name']
precio_mas_caro = chipo.loc[fila_maxima, 'item_price']


print(f"El producto más caro es: {articulo_mas_caro}")
print(f"Su precio es: ${precio_mas_caro}")

El producto más caro es: Chips and Fresh Tomato Salsa
Su precio es: $44.25

### Step 4. How many products cost more than $10.00?

In [61]:
print(chipo.loc[chipo["unit_price"] > 10, "item_name"].unique())
print(chipo.loc[chipo["unit_price"] > 10, "item_name"].nunique())

<StringArray>
[         'Chicken Bowl',         'Steak Burrito',       'Chicken Burrito',
         'Barbacoa Bowl',        'Veggie Burrito',           'Veggie Bowl',
    'Chicken Soft Tacos',            'Steak Bowl',      'Carnitas Burrito',
         'Carnitas Bowl',      'Barbacoa Burrito',    'Chicken Salad Bowl',
 'Barbacoa Crispy Tacos',     'Veggie Salad Bowl',         'Chicken Salad',
      'Steak Salad Bowl',  'Chicken Crispy Tacos',     'Veggie Soft Tacos',
   'Barbacoa Soft Tacos', 'Carnitas Crispy Tacos',   'Carnitas Salad Bowl',
   'Barbacoa Salad Bowl',      'Steak Soft Tacos',   'Carnitas Soft Tacos',
    'Steak Crispy Tacos']
Length: 25, dtype: str
25

In [62]:
chipo[chipo["unit_price"] > 10.00][["item_name", "item_price"]] #lo de dentro de dobles corchetes es una lista

               item_name  item_price
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
39         Barbacoa Bowl       11.75
...                  ...         ...
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1034 rows x 2 columns]

In [63]:
chipo_filtered = chipo.drop_duplicates(['item_name', 'choice_description'])
caros = chipo_filtered[(chipo_filtered['quantity'] == 1) & (chipo_filtered['item_price'] > 10.0)]
print(len(caros))

682

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [64]:
chipo['product_price'] = chipo['item_price'] / chipo['quantity']
print(len(chipo[chipo['product_price'] > 10.0]))
chipo['product_price'] = chipo['item_price'] / chipo['quantity']
print(chipo[chipo['product_price'] > 10.0]['order_id'].nunique())

1034
787

In [65]:
print(chipo.loc[chipo["unit_price"] > 10, "order_id"].nunique()) #miramos en los id explícitos, en el id del pedido los que sean de precio mayor de 10 y que sean numeros unicos

787

In [66]:
chipo.loc[chipo["unit_price"]>10, ["order_id"]] # con los corchetes en order_id nos da un data set

      order_id
5            3
7            4
13           7
23          12
39          19
...        ...
4610      1830
4611      1830
4617      1833
4618      1833
4619      1834

[1034 rows x 1 columns]

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [67]:
pedidos_totales = chipo.groupby('order_id')['item_price'].sum() #groupby hace un bucle cre una columna de precio del pedido
print(len(pedidos_totales[pedidos_totales > 10.0]))

1834

In [68]:
precio = chipo[["item_price", "order_id"]]
print(precio)

      item_price  order_id
0           2.39         1
1           3.39         1
2           3.39         1
3           2.39         1
4          16.98         2
...          ...       ...
4617       11.75      1833
4618       11.75      1833
4619       11.25      1834
4620        8.75      1834
4621        8.75      1834

[4622 rows x 2 columns]

In [72]:
totales_pedido = precio.groupby(chipo["order_id"])["item_price"].sum()
(totales_pedido) # es un data Frame si se mete en un print se pierde su formato

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [76]:
totales = chipo.groupby('order_id')['item_price'].sum()
print(totales)

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [82]:
print(len(totales[totales > 10]))

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [33]:
pedidos_con_producto_caro = chipo[chipo['item_price'] > 10.0]['order_id'].nunique()
print(pedidos_con_producto_caro)

863

In [84]:
print(chipo.loc[(chipo["item_price"] >10) & (chipo["quantity"]>1), "order_id"].nunique())

117

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [34]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity']
result = chipo[['item_name', 'unit_price']]
print(result.head())

                               item_name  unit_price
0           Chips and Fresh Tomato Salsa        2.39
1                                   Izze        3.39
2                       Nantucket Nectar        3.39
3  Chips and Tomatillo-Green Chili Salsa        2.39
4                           Chicken Bowl        8.49

### Step 6. Sort by the name of the item

In [ ]:
chipo.sort_values(by='item_name') #que ordene por(by) item_name. con muchas columnas se indica por columna a ordenar (el orden suele ser primero numérico y luego alfabético)

,order_id,quantity,item_name,choice_description,item_price,unit_price,product_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49,6.49
...,...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [88]:
chipo_ordenado = chipo.sort_values(by='item_price', ascending=False).head(1)['quantity'].values[0]
print(chipo_ordenado)

15

In [92]:
idx_implicito = chipo["item_price"].argmax() #sobre chipo, numero de fila que me lo da argmax. calculando el indice implicito, numero consecutivo incambiable
print(idx_implicito)

3598

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [39]:
veggie_salad_orders = chipo[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()
print(veggie_salad_orders)

18

In [93]:
print((chipo["item_name"] == "Veggie Salad Bowl").sum())
print(chipo.loc[chipo["item_name"] == "Veggie Salad Bowl", "quantity"].sum())

18
18

### Step 9. How many times did someone order more than one Canned Soda?

In [40]:
print(len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]))

20

In [96]:
print(chipo.loc[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"]>1), "order_id"].nunique())

18

In [98]:
chipo.loc[chipo["order_id"] == 450]

,order_id,quantity,item_name,choice_description,item_price,unit_price,product_price
1091,450,2,Canned Soda,[Dr. Pepper],2.18,1.09,1.09
1092,450,2,Canned Soda,[Coca Cola],2.18,1.09,1.09
1093,450,1,Steak Burrito,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",11.48,11.48,11.48